branches:
  only: 
    - next
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd ../demo && npm run build.plugin && npm run ci.tslint
    - stage: "Build and webpack"
      os: osx
      env:
        - Webpack="iOS"
      osx_image: xcode9.2
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script:
        - cd ../demo && tns platform add ios@next
        - cd ../demo-angular && tns platform add ios@next
      script:
        - cd ../demo && npm run build.plugin && npm i && tns build ios --bundle --env.uglify
        - cd ../publish && sh pack.sh && cp package/*.tgz ../demo-angular/package.tgz
        - cd ../demo-angular && tns plugin add package.tgz && npm i && tns build ios --bundle --env.uglify --env.aot
    - os: linux
      language: android
      env:
        - Webpack="Android"
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      before_script:
        - cd ../demo && tns platform add android@next
        - cd ../demo-angular && tns platform add android@next
      script:
        - cd ../demo && npm run build.plugin && npm i && tns build android --bundle --env.uglify
        - cd ../publish && sh pack.sh && cp package/*.tgz ../demo-angular/package.tgz
        - cd ../demo-angular && tns plugin add package.tgz && npm i && tns build android --bundle --env.uglify --env.aot
    - os: linux
      env: 
        - BuildAndroid="26"
      language: android
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      before_script:
        - cd ../demo && tns platform add android@next
        - cd ../demo-angular && tns platform add android@next
      script:
        - cd ../src && npm i && npm run tsc && cd ../demo && tns build android && cd ../demo-angular && tns build android
    - os: osx
      env: 
        - BuildiOS="11"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script:
        - cd ../demo && tns platform add ios@next
        - cd ../demo-angular && tns platform add ios@next
      script: 
        - cd ../src && npm i && npm run tsc && cd ../demo && tns build ios && cd ../demo-angular && tns build ios

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-26
    - android-23
    - extra-android-m2repository

install:
    - echo no | npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd src
    - npm uninstall tns-core-modules -D && npm install tns-core-modules@next -D
    - cd ../demo
    - npm uninstall nativescript-dev-webpack -D && npm install nativescript-dev-webpack@next -D
    - ./node_modules/.bin/update-ns-webpack --deps
    - npm uninstall tns-core-modules -P && npm install tns-core-modules@next -P
    - npm uninstall nativescript-dev-typescript -D && npm install nativescript-dev-typescript@next -D
    - cd ../demo-angular
    - npm uninstall nativescript-dev-webpack -D && npm install nativescript-dev-webpack@next -D
    - ./node_modules/.bin/update-ns-webpack --deps
    - ./node_modules/.bin/update-app-ng-deps
    - npm uninstall tns-core-modules -P && npm install tns-core-modules@next -P
    - npm uninstall nativescript-angular -P && npm install nativescript-angular@next -P
    - npm uninstall nativescript-dev-typescript -D && npm install nativescript-dev-typescript@next -D
